sonar.projectKey=foodranker-restaurant-service
sonar.projectName=FoodRanker - Restaurant Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.coverage.exclusions=src/server.js,src/config/db.js,src/models/restaurant.model.js,src/middlewares/auth.middleware.js,src/utils/google-places.util.js,src/utils/overpass.util.js,src/utils/broker.util.js,src/utils/consumer.js,src/utils/jwt.util.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# El scanner corre montando solo esta carpeta (sin .git del monorepo)
sonar.scm.disabled=true
