ingress:
  - hostname: grpc-media.foodsranker.com
    service: http://media-service:50051
    originRequest:
      http2Origin: true

  - hostname: auth.foodsranker.com
    service: http://auth-service:3000

  - hostname: users.foodsranker.com
    service: http://user-service:3001

  - hostname: restaurants.foodsranker.com
    service: http://restaurant-service:3003

  - hostname: reviews.foodsranker.com
    service: http://review-service:3004

  - hostname: media.foodsranker.com
    service: http://media-service:3005

  - hostname: social.foodsranker.com
    service: http://social-service:3006

  - hostname: notifications.foodsranker.com
    service: http://notification-service:3007

  - hostname: media-storage.foodsranker.com
    service: http://minio:9000

  - service: http_status:404
